### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by seyioyemade** [Bestbynature/TodoList-webpack-ES6#13]
# Peer to peer review

You've done a really good job @Bestbynature 👍 🍾 🍾  

♻️ But there are few recommendations I will like to make. 

- [ ] I would suggest users should be asked the maximum number of slots they want.
- [ ] I would also like to suggest that users should be given the option to increment their slots by one each time they exhaust the allocated slots.
- [ ] Users could also have a popup displayed asking them if they need more slots when they exhaust the allocated one.
- [ ] The borders can be removed to improve the application's look and feel.

**Comment by Bestbynature** [comment]
#### Thank you so much @seyioyemade for the observations and recommendations. The issues raised have been fixed. Thank you 👍
