### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by rosemutai** [Bestbynature/TodoList-webpack-ES6#15]
Hi @Bestbynature. You have really done a great job implementing all the requirements needed. Congratulations on also customizing this project. 🍾 🍾 🍾🍾

**Comment by Bestbynature** [comment]
![jingle all the way thank you GIF](https://user-images.githubusercontent.com/104390780/233843240-9dd71dc1-2081-4439-8085-87ef7f7b6b13.gif)
**Thanks, @rosemutai for your keen observation. Feel free to let me know if you later spot anything that needs to be changed in the application. I appreciate you.**
